<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Book Now</name>
   <tag></tag>
   <elementGuidId>6f12e225-f4eb-451b-8449-cdbb451998cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='Salons']/div/div/div/a/div/div/div[3]/a/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>6ad62a7b-5b73-416a-a12c-5b8e984cca75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f9edf86a-b208-4ea5-8012-357fd1078437</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Book Now</value>
      <webElementGuid>66cdf73a-fcca-4650-a72c-950294a8e328</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Salons&quot;)/div[@class=&quot;flex w-full justify-center items-center 2xl:px-20 bg-white&quot;]/div[@class=&quot;flex flex-col md:p-12 py-4 px-4&quot;]/div[@class=&quot;flex flex-wrap mt-6 justify-around&quot;]/a[1]/div[@class=&quot;my-4 mx-6&quot;]/div[@class=&quot;card&quot;]/div[@class=&quot;btn&quot;]/a[@class=&quot;fancy&quot;]/a[@class=&quot;text&quot;]</value>
      <webElementGuid>8a05a1e2-9fbe-444d-a5b6-f3647fb9f633</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Salons']/div/div/div/a/div/div/div[3]/a/a</value>
      <webElementGuid>442e87b6-a855-43c8-b203-4618cdb41797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Book Now')]</value>
      <webElementGuid>17170ce8-35af-493b-b6da-848dd5965d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connect your account to make a appointment with the barber of your choice!'])[1]/following::a[3]</value>
      <webElementGuid>572617b3-d41b-4d06-aec7-4bdef5e8e8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('Barber', &quot;'&quot;, 's Shops')])[1]/following::a[3]</value>
      <webElementGuid>5cf8ba4a-5978-461c-b253-e9efb78987d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Now'])[2]/preceding::a[1]</value>
      <webElementGuid>40af8968-ca26-48f3-ade3-8854601037d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SHOW ALL BARBERS'])[1]/preceding::a[4]</value>
      <webElementGuid>05b1a7a6-2dfe-403d-b7b4-0806c8cb66a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Book Now']/parent::*</value>
      <webElementGuid>10228870-8843-4853-a7f2-9bb71a2e4db1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/a</value>
      <webElementGuid>8d376168-64ca-484b-8eb8-2be30b403310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'Book Now' or . = 'Book Now')]</value>
      <webElementGuid>110357a1-8bc5-4821-823a-36e05e89d4c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
