<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Book Appointment</name>
   <tag></tag>
   <elementGuidId>33ab5796-2316-4a14-8cbd-df4c28571af8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type='button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>fd5762dd-92e0-4bb4-abe9-4c06b103c760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7237366a-c961-4024-a433-fad4350965e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-12 w-full rounded font-medium text-base bg-[#0f0e13] text-white</value>
      <webElementGuid>eb9fb4ac-b99e-4936-b37a-0f213b57eb9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Book Appointment</value>
      <webElementGuid>5e221590-88f3-49bc-9d6e-9653f8dc04f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;gradient-bg-welcome pb-4 flex md:flex-row flex-col w-full justify-center items-center&quot;]/div[@class=&quot;text-[#37c7da] flex-[0.3]&quot;]/div[1]/div[@class=&quot;max-w-md bg-white shadow-lg rounded-lg md:max-w-xl&quot;]/div[@class=&quot;md:flex&quot;]/div[@class=&quot;w-full px-7 py-8&quot;]/div[@class=&quot;flex justify-between items-center pt-2&quot;]/button[@class=&quot;h-12 w-full rounded font-medium text-base bg-[#0f0e13] text-white&quot;]</value>
      <webElementGuid>69ec46b5-b20e-4698-b498-f8d7f7f7e46d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@type='button']</value>
      <webElementGuid>175d4bd0-74a5-4754-8f36-fd454d8d9684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/div/div/div/div[7]/button</value>
      <webElementGuid>97c1b195-159c-4195-b185-0852b47e1abd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Book Now!'])[1]/following::button[1]</value>
      <webElementGuid>015956cc-b6a6-4974-bf5c-b30debb91d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::button[1]</value>
      <webElementGuid>ebfac2d7-b955-416f-b8f3-9d5be77bc0f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Packages Details'])[1]/preceding::button[1]</value>
      <webElementGuid>63400e6f-3421-4b83-aa06-5d43bc2fa70f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Basic Plan'])[1]/preceding::button[1]</value>
      <webElementGuid>5bdd6686-0da6-4b2e-9048-f2df6b2cf55e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Book Appointment']/parent::*</value>
      <webElementGuid>9e244894-fa89-4a40-9af7-ec6adaaeed10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>2aec8e64-7249-4825-8fa8-c97ff85391a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Book Appointment' or . = 'Book Appointment')]</value>
      <webElementGuid>45785a58-f32f-422a-9ccb-f77cb8be0dfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
