<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Book Now_cname</name>
   <tag></tag>
   <elementGuidId>e4cc2325-3763-4dc3-970f-241b0cb6e0ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;cname&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='cname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c22b1b3e-f18e-491d-8012-e648b82ff415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>16644b66-8d82-4a59-ae96-cd365248eabb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cname</value>
      <webElementGuid>81854cec-9593-4530-94fe-5f0131d4fa15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border rounded h-10 w-full focus:outline-none focus:border-green-200 px-2 mt-2 text-sm</value>
      <webElementGuid>125c72a7-3503-495e-a308-94739b537b4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Customer Name</value>
      <webElementGuid>9f25b1dd-6d73-463f-ac21-7d8e5ec6e20e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>bravo</value>
      <webElementGuid>a15eae5e-03dd-49c0-98f4-8066e54aa579</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;gradient-bg-welcome pb-4 flex md:flex-row flex-col w-full justify-center items-center&quot;]/div[@class=&quot;text-[#37c7da] flex-[0.3]&quot;]/div[1]/div[@class=&quot;max-w-md bg-white shadow-lg rounded-lg md:max-w-xl&quot;]/div[@class=&quot;md:flex&quot;]/div[@class=&quot;w-full px-7 py-8&quot;]/div[@class=&quot;relative pb-5&quot;]/input[@class=&quot;border rounded h-10 w-full focus:outline-none focus:border-green-200 px-2 mt-2 text-sm&quot;]</value>
      <webElementGuid>7eae9e56-2e74-4070-8260-d25ad8bf166d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='cname']</value>
      <webElementGuid>b7f33f66-faa3-4561-bb04-915e1d09d931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/div/div/div/div[2]/input</value>
      <webElementGuid>85571952-6604-482c-9379-43978d9280bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b6014cc8-a49f-4008-a505-dbceea7773f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'cname' and @placeholder = 'Customer Name']</value>
      <webElementGuid>2605ee6a-faa5-43fb-aa17-b46c75922af0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
