<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Get your FREE Account_email</name>
   <tag></tag>
   <elementGuidId>40f4b7eb-5ed5-4599-859b-c8d968d514da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;email&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6441d79d-8a3a-40d1-99ec-885b4caf1c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>pl-2 w-full outline-none border-none</value>
      <webElementGuid>33c376d9-c928-4c34-96d3-bfb95c86ba40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>75caedb0-a2fd-4aae-a38b-36848bc16d13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>69066c67-9ed2-498e-b213-2a02ef06488d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>ba29be40-2182-4e27-9263-214645c0c17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;h-screen flex&quot;]/div[@class=&quot;flex w-full lg:w-1/2 justify-center items-center bg-[#f2f9ff] space-y-8&quot;]/div[@class=&quot;w-full&quot;]/form[@class=&quot;bg-white rounded-md shadow-2xl p-12 w-full&quot;]/div[@class=&quot;flex items-center border-2 mb-6 py-2 px-3 rounded-2xl&quot;]/input[@class=&quot;pl-2 w-full outline-none border-none&quot;]</value>
      <webElementGuid>b6ddab04-184c-42f7-8c18-48398baf3583</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='email']</value>
      <webElementGuid>79bbcd7d-4e6f-4ab0-b8a1-494103c88045</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/form/div[2]/input</value>
      <webElementGuid>63f22f17-a79d-4f5e-ab8b-a35d34053e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>14471f14-048e-4d0d-97b2-17672e68594b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'email' and @placeholder = 'Email' and @name = 'email']</value>
      <webElementGuid>0cf750b1-e83e-4ebc-8cec-2d7572153864</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
