<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Salon Owner_avatar</name>
   <tag></tag>
   <elementGuidId>eeaf2a24-45a0-44ab-b2ac-ef5d09925f72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;avatar&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='avatar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7baf652f-ef3b-4e39-934c-fdc37be1d722</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-full outline-none border-2 bg-indigo-100 p-1 text-sm </value>
      <webElementGuid>d135bc02-3574-4325-9bcb-024de0098e89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>6807e867-c4f7-4bbf-968d-6a713c9cbfc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>avatar</value>
      <webElementGuid>d9010e21-0ac2-464f-85d9-4aa2f23011eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/*</value>
      <webElementGuid>0d3b8933-f9c9-4f50-9269-23a986c66743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;h-screen flex&quot;]/div[@class=&quot;flex w-full lg:w-1/2 justify-center items-center bg-[#f2f9ff] space-y-8&quot;]/div[@class=&quot;w-full&quot;]/form[@class=&quot;bg-white rounded-md shadow-2xl p-12 w-full&quot;]/div[@class=&quot;flex items-center border-2 mb-8 py-3 px-3 rounded-2xl&quot;]/input[@class=&quot;w-full outline-none border-2 bg-indigo-100 p-1 text-sm&quot;]</value>
      <webElementGuid>d1b37fff-d9e6-417e-a75d-81d2c2e3b089</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='avatar']</value>
      <webElementGuid>50e4bd2b-5c51-44be-82c4-e37ae71024d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/form/div[5]/input</value>
      <webElementGuid>858e6759-3203-424d-a028-f980d4d7f3b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>bb6fb989-aba3-4984-914a-b35f25cef938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'avatar']</value>
      <webElementGuid>0e21f996-cae3-4c53-a4fc-d1c1ba273c6a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
