<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Submit Your Review ForAlex BarberBarber_submitDialogTextArea</name>
   <tag></tag>
   <elementGuidId>32387be1-3dc1-4a61-adbf-d086be6fdd18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>textarea.submitDialogTextArea</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[4]/div/div/div/div/div/textarea</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>426e0104-feec-48a4-bad3-5886555910d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>submitDialogTextArea</value>
      <webElementGuid>16c07a4b-de64-4927-9542-9b4fba797ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>a73b2aa6-e434-4a54-8009-a97c48296d18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>7</value>
      <webElementGuid>bac34d1f-d7dd-4564-94d4-e2b7f2248742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[4]/div[1]/div[@class=&quot;flex flex-col sm:flex-row bg-black justify-around&quot;]/div[@class=&quot;min-w-md  bg-white shadow-lg rounded-lg md:max-w-xl my-14 w-full sm:w-1/2&quot;]/div[@class=&quot;md:flex font-cursive&quot;]/div[@class=&quot;w-full px-6 py-6 flex flex-col&quot;]/textarea[@class=&quot;submitDialogTextArea&quot;]</value>
      <webElementGuid>9ca6083d-c6bc-4a29-b8b1-d6e994175925</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[4]/div/div/div/div/div/textarea</value>
      <webElementGuid>d2cb4f41-7b12-46cf-9126-ea6bfbcc8054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>d80381fa-ab83-4385-96f3-03500f2200de</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
