<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Create Barber_barbername</name>
   <tag></tag>
   <elementGuidId>fb37467d-339d-4ecb-b221-683f48563587</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#barbername</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='barbername']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>909cc3db-a77b-4d1a-8547-295b47d14f81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>barbername</value>
      <webElementGuid>5f06eed3-a64e-4357-ad3d-8990667bd49e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ab1ad51d-d25f-4acc-af0f-d04d77cc109e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>09e02e53-2153-46ba-9dc4-4c98c1792bdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;barbername&quot;)</value>
      <webElementGuid>28a91f41-05ec-487a-9333-0fc17066fa37</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='barbername']</value>
      <webElementGuid>69b4c37c-c685-4320-8ec8-dd81c6198305</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/form/div[2]/input</value>
      <webElementGuid>d2affcdb-8671-4cf4-99d6-5dfbad1a58d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>10ec72cc-ade8-4edd-a1e2-2b2456037459</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'barbername' and @type = 'text']</value>
      <webElementGuid>b1a0891c-83ec-4d64-a5fa-edeb15236c68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
