<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Barber Name_worksat</name>
   <tag></tag>
   <elementGuidId>e50856f6-e540-40e9-9578-6b925a84fb37</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#worksat</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='worksat']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5524f6e0-2d44-46fb-b3d4-dd3aa12bed09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>worksat</value>
      <webElementGuid>42b24138-9901-4118-a7e7-dc8907d0e022</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b558865c-011f-4637-bbb3-cf8769daa51e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>343dabd4-5d33-4e9d-a1e3-d9233f6f0652</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;worksat&quot;)</value>
      <webElementGuid>d5bbe27d-c210-4ea8-9afa-a5b518436041</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='worksat']</value>
      <webElementGuid>b44bb167-ebfa-4d4f-84cd-eed7edc94512</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/form/div[3]/input</value>
      <webElementGuid>10f0af03-1143-4b31-85c0-57b65be81f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>0266c4bf-9842-43db-9f73-fb2ce157df5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'worksat' and @type = 'text']</value>
      <webElementGuid>d660fb05-a06c-4a3b-9f5e-c8fe0b181a44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
