<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Experience_avatar</name>
   <tag></tag>
   <elementGuidId>1b205803-345b-414c-a34d-ae05497b5c9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;avatar&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='avatar']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2fca4ded-fc8d-4131-9de9-37dbc702e3ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input createProductFormFile</value>
      <webElementGuid>6335106a-ce8a-49df-8e4a-d6e3075277bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>d73083a7-bc56-47b4-83d4-48e7fd195d63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>avatar</value>
      <webElementGuid>ceda980a-e033-479b-9046-268ded6b04ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>image/*</value>
      <webElementGuid>11bf5894-e5c0-4da7-9a89-6efabc2fd948</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;dashboard&quot;]/div[@class=&quot;newProductContainer&quot;]/form[@class=&quot;form&quot;]/div[@class=&quot;input-container ic2&quot;]/input[@class=&quot;input createProductFormFile&quot;]</value>
      <webElementGuid>54b91b22-c0a5-47ac-a9cf-2495dcd41fb8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='avatar']</value>
      <webElementGuid>fb4bd76b-4714-428a-9ab8-4b18fed800bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/form/div[6]/input</value>
      <webElementGuid>20b0541b-2015-4bc5-a2ee-6f9536ecdb8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/input</value>
      <webElementGuid>0d14ae20-afd7-44d9-b921-ebe78352d3c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @name = 'avatar']</value>
      <webElementGuid>7ebaf010-997e-4ddc-9c52-0b284a1d58ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
