<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Works At_timings</name>
   <tag></tag>
   <elementGuidId>745d95aa-c7bf-446b-bb04-436392c686d9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#timings</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='timings']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7b6f8019-8853-4d27-8687-bb324274f1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>timings</value>
      <webElementGuid>3437a43e-5a79-414d-9134-5e02ac33d546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f9f25f73-0056-4584-939e-ab9e37942a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>24e94aeb-a942-42ba-aae8-682fed4a9b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;timings&quot;)</value>
      <webElementGuid>8e189f61-4eb6-40be-ad00-711781452109</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='timings']</value>
      <webElementGuid>0024d778-ff00-4263-89e9-fda6a160dae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/form/div[4]/input</value>
      <webElementGuid>78544d27-1a50-4bdb-a9d1-1cbeee2f6776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>5514cfc5-5963-406f-98f1-b832437028e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'timings' and @type = 'text']</value>
      <webElementGuid>96e6a2d7-01a9-40cf-85d3-cf44c7d362ab</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
