<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Timings_experience</name>
   <tag></tag>
   <elementGuidId>0c5a879a-3cc1-4122-93fa-1eaf4525928a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#experience</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='experience']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>17dd180e-b553-4b21-9011-df6fb39c9947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>experience</value>
      <webElementGuid>5d95d639-8416-4c64-ad90-c87190957f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>322f5061-2bb1-4c1c-8633-80f506c9e0ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>381e75a6-baf8-4a35-9449-e8320eaaac4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;experience&quot;)</value>
      <webElementGuid>857a8e02-9b0d-4356-a76a-fe9c3deb394e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='experience']</value>
      <webElementGuid>b3d8e373-26b5-45bf-98cc-97bdea83605d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/form/div[5]/input</value>
      <webElementGuid>aecf165d-9458-4177-b058-6aba6c6c8079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/input</value>
      <webElementGuid>cd03e5e8-0c8d-4034-a717-b3b604f13c4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'experience' and @type = 'text']</value>
      <webElementGuid>da1c5dae-1825-4597-a204-f2a44ddfbc68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
