<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_1pm-6pm</name>
   <tag></tag>
   <elementGuidId>d41f2eec-966f-4457-810d-d123ce723447</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/div/div[2]/div[2]/div/div/div/div/div/div[7]/div[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>09e62119-b835-4fd4-b935-8ab5be51ef70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiDataGrid-cell MuiDataGrid-cell--textLeft</value>
      <webElementGuid>52f54e7d-2fc1-4898-ba49-5d0d9f5f081d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>e25c5b86-7573-4426-b9b1-ba3f6a8db54b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>1pm-6pm</value>
      <webElementGuid>4633a584-39ce-4f59-9d47-f9a4f0b82f9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field</name>
      <type>Main</type>
      <value>timings</value>
      <webElementGuid>ef9b7e9d-db16-439d-8b84-561d6a933ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rowindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>a3d89444-eccc-4a0a-95e6-4e56fb2711fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-colindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>8e3a5e84-c430-4460-b1aa-d831b9aaf84e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rowselected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5f9f65d6-7f5c-4cdb-8553-acd8afdb8f73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-editable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d7ce329d-d4d3-40af-a1f9-8eddf36509ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mode</name>
      <type>Main</type>
      <value>view</value>
      <webElementGuid>493e411c-cd74-4e90-93eb-92eb52b2aa38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>5c4b65ae-737b-4b0b-a821-aec21de4a55d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6cc3b4f6-afbe-405d-8b0e-24c8b50d3d42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1pm-6pm</value>
      <webElementGuid>7ce4dbbc-7881-43cd-b02c-de838d7a8928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;dashboard&quot;]/div[@class=&quot;productListContainer&quot;]/div[@class=&quot;MuiDataGrid-root MuiDataGrid-root productListTable MuiDataGrid-autoHeight&quot;]/div[@class=&quot;MuiDataGrid-main&quot;]/div[2]/div[@class=&quot;MuiDataGrid-windowContainer&quot;]/div[@class=&quot;MuiDataGrid-window&quot;]/div[@class=&quot;MuiDataGrid-dataContainer&quot;]/div[@class=&quot;MuiDataGrid-viewport&quot;]/div[@class=&quot;MuiDataGrid-renderingZone&quot;]/div[@class=&quot;Mui-even MuiDataGrid-row&quot;]/div[@class=&quot;MuiDataGrid-cell MuiDataGrid-cell--textLeft&quot;]</value>
      <webElementGuid>bc25cc76-8af5-402f-9327-29fe83e5748c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/div[2]/div[2]/div/div/div/div/div/div[7]/div[4]</value>
      <webElementGuid>95cb63d3-d32b-434d-a28b-b715c10c7cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ABCD Salon'])[1]/following::div[1]</value>
      <webElementGuid>dadcd2ee-45dd-41f8-ac74-11b608e6c670</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EFGH Barber'])[1]/following::div[2]</value>
      <webElementGuid>4e6d0406-59b8-4e0c-83ab-ad622a004b1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get connected with us on social networks:'])[1]/preceding::div[14]</value>
      <webElementGuid>c4064fc7-4316-42e9-852f-c985d9e4fd87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Barbera'])[1]/preceding::div[17]</value>
      <webElementGuid>f8f7c5da-b412-46a1-9825-8745557c9fcd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1pm-6pm']/parent::*</value>
      <webElementGuid>c97a0fb2-6aab-4365-b77e-4bcffd90a210</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[4]</value>
      <webElementGuid>6fb8c31d-3a4a-4677-a1a8-2d306e876e92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '1pm-6pm' or . = '1pm-6pm')]</value>
      <webElementGuid>17eaf572-7894-4ea2-ab64-fd3555a9eb31</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
