<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_ABCD Salon</name>
   <tag></tag>
   <elementGuidId>a4d1e274-44fd-4762-adf8-19ba6878ec1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/div/div[2]/div[2]/div/div/div/div/div/div[7]/div[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3c5e2332-2152-459c-a0d3-756440946674</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiDataGrid-cell MuiDataGrid-cell--textLeft</value>
      <webElementGuid>d3aea7fa-f7d0-414f-9a46-dc20e35a687c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>cell</value>
      <webElementGuid>ddb88f4a-432e-4031-9ada-d8d2fe50acf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>ABCD Salon</value>
      <webElementGuid>89383c4f-62e7-4e43-b03f-06f3026bcda4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-field</name>
      <type>Main</type>
      <value>worksAt</value>
      <webElementGuid>3810fa97-6f80-4537-8a3c-8cbf8fa6bd44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rowindex</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>329a75d7-abc7-41b0-8080-24545fbe056b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-colindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>3ef108c4-df01-4b10-94ca-f9f179465385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rowselected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>fdbcbdc2-d682-4691-b0e3-e983974b7860</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-editable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2956648e-4a13-4e78-9f9b-f7e90d1b438b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-mode</name>
      <type>Main</type>
      <value>view</value>
      <webElementGuid>659a5cff-3822-4f61-9245-91cb6ea9dede</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-colindex</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>59f95b12-aafa-4a31-9f68-0ce7ae5408d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>7db3f75d-0807-48a8-ba76-7aa99d56c511</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ABCD Salon</value>
      <webElementGuid>5a0d983e-1f97-4a91-a72f-04cf5ceaed1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;dashboard&quot;]/div[@class=&quot;productListContainer&quot;]/div[@class=&quot;MuiDataGrid-root MuiDataGrid-root productListTable MuiDataGrid-autoHeight&quot;]/div[@class=&quot;MuiDataGrid-main&quot;]/div[2]/div[@class=&quot;MuiDataGrid-windowContainer&quot;]/div[@class=&quot;MuiDataGrid-window&quot;]/div[@class=&quot;MuiDataGrid-dataContainer&quot;]/div[@class=&quot;MuiDataGrid-viewport&quot;]/div[@class=&quot;MuiDataGrid-renderingZone&quot;]/div[@class=&quot;Mui-even MuiDataGrid-row&quot;]/div[@class=&quot;MuiDataGrid-cell MuiDataGrid-cell--textLeft&quot;]</value>
      <webElementGuid>64d74d8b-e5c0-4555-a292-c14e9aedba82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/div/div[2]/div[2]/div/div/div/div/div/div[7]/div[3]</value>
      <webElementGuid>a0af9e9c-0745-4bbb-a92a-c77c4e4ab072</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EFGH Barber'])[1]/following::div[1]</value>
      <webElementGuid>6117ec6c-257c-4a16-92c8-6515916ed091</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shah Barbers'])[1]/following::div[7]</value>
      <webElementGuid>57b412ec-c05e-4cda-8b38-3ef1008c40c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Get connected with us on social networks:'])[1]/preceding::div[15]</value>
      <webElementGuid>1420dbaf-6ff3-4db0-97d3-64d0105dce21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Barbera'])[1]/preceding::div[18]</value>
      <webElementGuid>34d619a0-111d-43fc-ac82-212a300dd064</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ABCD Salon']/parent::*</value>
      <webElementGuid>3349df68-05f3-461a-b857-1901760fb665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div[3]</value>
      <webElementGuid>ada6d24b-f079-4705-9eb1-677f734992ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'ABCD Salon' or . = 'ABCD Salon')]</value>
      <webElementGuid>9a55b139-df6b-4b4b-aa8f-cd9b8c72e766</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
