<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_All Salons</name>
   <tag></tag>
   <elementGuidId>8db8169c-1a85-451f-9867-a4bf1882489f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#productListHeading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='productListHeading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>da088428-10ef-44ca-bc0c-998fb994eb9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>productListHeading</value>
      <webElementGuid>382b5c59-2ed0-4683-a20c-8c02032b7f34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Salons</value>
      <webElementGuid>4ba7e3e3-1538-4560-9111-8336464add54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productListHeading&quot;)</value>
      <webElementGuid>378b317d-355e-4223-9d1e-6ff8d8f2d894</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='productListHeading']</value>
      <webElementGuid>6d4c05ce-1f0f-4f39-ae8f-1c5137ce1373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/h1</value>
      <webElementGuid>80615fe3-d7e0-449f-b360-a5efe1adb785</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bravo'])[1]/following::h1[1]</value>
      <webElementGuid>7ab51643-a3b4-46fb-9c31-146f192c2034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi,'])[1]/following::h1[1]</value>
      <webElementGuid>db8e0f23-420d-4b53-bc86-07fffe656b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No rows'])[1]/preceding::h1[1]</value>
      <webElementGuid>375c43eb-4435-46fa-be06-82bd16abdd82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salon ID'])[1]/preceding::h1[1]</value>
      <webElementGuid>82f0ed76-108d-4bb4-b025-f0bee6ad7e0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>3c90595c-e441-4e0b-9e8c-239bdf19955b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'productListHeading' and (text() = 'All Salons' or . = 'All Salons')]</value>
      <webElementGuid>f99fd4cc-9d13-4e54-a420-53485b6ca97a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
