<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Create Salon_salonname</name>
   <tag></tag>
   <elementGuidId>9617e586-5b1f-4c2d-af5e-dade832ca967</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#salonname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='salonname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20b5a699-b7de-4115-a67b-8d264d12435b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>salonname</value>
      <webElementGuid>9e8f76e2-e00a-4b29-a52e-db082c1aa1e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa93ae1f-72f8-4c89-a823-441adbdc7dc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3656777-cea8-4860-a0e6-d7b4a15aa694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;salonname&quot;)</value>
      <webElementGuid>e0c38c15-1746-426b-a140-b87907772d00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='salonname']</value>
      <webElementGuid>d517eaf0-226b-4428-924a-bf37a16ba8c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/form/div[2]/input</value>
      <webElementGuid>75d491e0-85c1-4acb-8d85-3e230d74feef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>a9d7640b-86c4-4222-b01c-19d0dee68e34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'salonname' and @type = 'text']</value>
      <webElementGuid>c10cbba5-0d65-4b46-acc6-51916346b9f6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
