<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Salon Name_timings</name>
   <tag></tag>
   <elementGuidId>85e88f6f-1990-4ea1-9d49-ce80534697a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#timings</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='timings']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7908c6bf-60b5-47f6-a12f-6c0cf7dae3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>timings</value>
      <webElementGuid>bfeb82d8-9675-4309-9423-e45173a64ca6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9a509d3-056f-44f4-b7b1-5a5ee80ed640</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5b037d21-2e72-452c-8563-3fe56375a67f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;timings&quot;)</value>
      <webElementGuid>a11646e3-ac76-4e72-81a6-f69029e0cb27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='timings']</value>
      <webElementGuid>3107dd5a-8e44-4f7a-a185-16530c01cf57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/form/div[3]/input</value>
      <webElementGuid>301163e3-028c-4349-b18e-51d4e13532fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>9b53c355-11f3-4f1d-abc7-5b961cd5275e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'timings' and @type = 'text']</value>
      <webElementGuid>588b552d-1f26-4d4a-83a8-9c406cf91a5e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
