<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_bravo</name>
   <tag></tag>
   <elementGuidId>227c8e67-a5df-4e97-bebc-0856bc40b451</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[4]/div/div/div[2]/div/table/tbody/tr[7]/td[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>1e73e588-7202-401c-9ce2-dc9d9aabe570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border__style</value>
      <webElementGuid>df6abc8d-191e-4f66-a586-14288351a83a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>bravo</value>
      <webElementGuid>52a59f89-5267-4ee0-ae78-43f2142d9493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[4]/div[1]/div[@class=&quot;flex flex-col sm:flex-row bg-black justify-around&quot;]/div[@class=&quot;w-full sm:w-1/2 my-12 flex flex-col content-center items-center&quot;]/div[1]/table[@class=&quot;bg-white border__style text-center&quot;]/tbody[1]/tr[7]/td[@class=&quot;border__style&quot;]</value>
      <webElementGuid>7e0db90e-62f5-4b86-8d69-cc5528e177b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[4]/div/div/div[2]/div/table/tbody/tr[7]/td[2]</value>
      <webElementGuid>69291aca-0b4b-4725-b2a9-1f5a31b1418b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='stevie G'])[1]/following::td[2]</value>
      <webElementGuid>e8e0cfa0-e902-49af-b9a1-b85f7ffa8ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='shayan'])[1]/following::td[4]</value>
      <webElementGuid>e9713b11-ce18-4615-95cc-55093a4545ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nice Barberdsfsddfs'])[1]/preceding::td[1]</value>
      <webElementGuid>63d39945-3ce9-4b75-9e63-716e3887867d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='bravo']/parent::*</value>
      <webElementGuid>fd9f1337-b9da-4191-8146-e5308008ccec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]</value>
      <webElementGuid>7d803460-fe74-42f5-8aed-52b6251c6e44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'bravo' or . = 'bravo')]</value>
      <webElementGuid>352e11da-710c-490a-a96b-2ca2d07110fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
