<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h1_All Salons</name>
   <tag></tag>
   <elementGuidId>eba6148e-cc92-4bb8-b1bf-e6ba71118388</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#productListHeading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='productListHeading']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h1</value>
      <webElementGuid>dd44ae6a-1a24-41d8-ae50-b00867b01a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>productListHeading</value>
      <webElementGuid>180c1bf5-4af2-43f6-bb6d-a70a1a38f9c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>All Salons</value>
      <webElementGuid>a6ef7f1d-749b-4b68-b407-4a92ef5a56e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productListHeading&quot;)</value>
      <webElementGuid>3ca13b4a-27c1-4649-9344-40fbdbcce29f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h1[@id='productListHeading']</value>
      <webElementGuid>261f1e39-0bd6-4978-8f91-419a0c6bea5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/h1</value>
      <webElementGuid>06d0df1d-9d06-4f84-b4bd-fdeb881c9959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='bravo'])[1]/following::h1[1]</value>
      <webElementGuid>21b55e8c-b8c7-46fb-af7a-4e412b24fce8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi,'])[1]/following::h1[1]</value>
      <webElementGuid>123459be-c475-486f-b45c-f088b3a8cdab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salon ID'])[1]/preceding::h1[1]</value>
      <webElementGuid>9a427674-4c87-412d-9c8e-a799eaaa9c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salon Name'])[1]/preceding::h1[1]</value>
      <webElementGuid>fd228fc9-b68c-4e61-aeae-7a6088875499</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1</value>
      <webElementGuid>d1a088bc-da13-4429-b14a-404419aac588</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h1[@id = 'productListHeading' and (text() = 'All Salons' or . = 'All Salons')]</value>
      <webElementGuid>af331cfb-b785-44d9-b0bc-d69bf8fd1a7d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
